In [2]:
import pandas as pd
file = '/content/drive/MyDrive/Colab Notebooks/dio-pandas/data/Gapminder.csv'

In [59]:
df = pd.read_csv(file, delimiter=';', parse_dates=['year'])
# df = pd.read_csv(file, error_bad_lines=False, delimiter=';')
# df = pd.read_csv(file)

In [61]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [63]:
df.rename(columns={"country":"pais","continent":"continente","year":"ano","gdpPercap":"pibpercap"}, inplace=True)

In [64]:
df

             pais continente        ano  lifeExp       pop   pibpercap
0     Afghanistan       Asia 1952-01-01   28.801   8425333  779.445314
1     Afghanistan       Asia 1957-01-01   30.332   9240934  820.853030
2     Afghanistan       Asia 1962-01-01   31.997  10267083  853.100710
3     Afghanistan       Asia 1967-01-01   34.020  11537966  836.197138
4     Afghanistan       Asia 1972-01-01   36.088  13079460  739.981106
...           ...        ...        ...      ...       ...         ...
3307     Zimbabwe     Africa 1987-01-01   62.351   9216418  706.157306
3308     Zimbabwe     Africa 1992-01-01   60.377  10704340  693.420786
3309     Zimbabwe     Africa 1997-01-01   46.809  11404948  792.449960
3310     Zimbabwe     Africa 2002-01-01   39.989  11926563  672.038623
3311     Zimbabwe     Africa 2007-01-01   43.487  12311143  469.709298

[3312 rows x 6 columns]

In [17]:
df.dtypes

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

In [32]:
len(df['country'].unique())

187

In [35]:
len(df['continent'].unique())

7

In [43]:
filtro = df.continent.isnull()
df.loc[filtro].country.drop_duplicates()

60                    Armenia
64                      Aruba
72                  Australia
189                   Bahamas
223                  Barbados
308                    Belize
500                    Canada
1100            French Guiana
1101         French Polynesia
1134                  Georgia
1194                  Grenada
1202               Guadeloupe
1249                    Haiti
1273         Hong Kong, China
1865                 Maldives
1895               Martinique
1933    Micronesia, Fed. Sts.
2088     Netherlands Antilles
2096            New Caledonia
2290         Papua New Guinea
2467                  Reunion
2523                    Samoa
2530    Sao Tome and Principe
3059                    Tonga
3229               Uzbekistan
3233                  Vanuatu
Name: country, dtype: object

In [34]:
filtro1 = df.continet == Africa
df.groupby(['continent','country']).size()

continent  country
Africa     Algeria            12
           Angola             12
           Benin              12
           Botswana           12
           Burkina Faso       12
                              ..
FSU        Russia             20
           Ukraine            20
Oceania    Fiji               10
           New Zealand        55
           Solomon Islands     9
Length: 161, dtype: int64

In [65]:
filtro = df.ano.dt.year == 2007
df.loc[filtro]

                    pais continente        ano  lifeExp       pop     pibpercap
11           Afghanistan       Asia 2007-01-01   43.828  31889923    974.580338
23               Albania     Europe 2007-01-01   76.423   3600523   5937.029526
35               Algeria     Africa 2007-01-01   72.301  33333216   6223.367465
47                Angola     Africa 2007-01-01   42.731  12420476   4797.231267
59             Argentina   Americas 2007-01-01   75.320  40301927  12779.379640
...                  ...        ...        ...      ...       ...           ...
3263             Vietnam       Asia 2007-01-01   74.249  85262356   2441.576404
3275  West Bank and Gaza       Asia 2007-01-01   73.422   4018332   3025.349798
3287         Yemen, Rep.       Asia 2007-01-01   62.698  22211743   2280.769906
3299              Zambia     Africa 2007-01-01   42.384  11746035   1271.211593
3311            Zimbabwe     Africa 2007-01-01   43.487  12311143    469.709298

[183 rows x 6 columns]

In [53]:
df.shape

(3312, 6)

In [55]:
df.describe()

               ano      lifeExp           pop      pibpercap
count  3312.000000  3312.000000  3.312000e+03    3312.000000
mean   1980.301630    65.246871  3.161489e+07   11317.115805
std      16.927294    11.768412  1.041193e+08   11369.142739
min    1950.000000    23.599000  5.941200e+04     241.165877
25%    1967.000000    58.337500  2.678572e+06    2514.625266
50%    1982.000000    69.610000  7.557218e+06    7838.505123
75%    1996.000000    73.657750  1.958522e+07   17357.879170
max    2007.000000    82.670000  1.318683e+09  113523.132900

In [ ]:
filtro = df.ano.dt.year == 2007
df.loc[filtro].sort_values('lifeExp', ascending=False).head(10)

In [ ]:
filtro = df.ano.dt.year == 2007
df.loc[filtro].sort_values('pibpercap', ascending=False).head(50)

In [73]:
filtro = df.pais == 'Brazil'
df.loc[filtro].sort_values('lifeExp', ascending=False)

       pais continente        ano  lifeExp        pop    pibpercap
386  Brazil   Americas 2007-01-01   72.390  190010647  9065.800825
385  Brazil   Americas 2002-01-01   71.006  179914212  8131.212843
384  Brazil   Americas 1997-01-01   69.388  168546719  7957.980824
383  Brazil   Americas 1992-01-01   67.057  155975974  6950.283021
382  Brazil   Americas 1987-01-01   65.205  142938076  7807.095818
381  Brazil   Americas 1982-01-01   63.336  128962939  7030.835878
380  Brazil   Americas 1977-01-01   61.489  114313951  6660.118654
379  Brazil   Americas 1972-01-01   59.504  100840058  4985.711467
378  Brazil   Americas 1967-01-01   57.632   88049823  3429.864357
377  Brazil   Americas 1962-01-01   55.665   76039390  3336.585802
376  Brazil   Americas 1957-01-01   53.285   65551171  2487.365989
375  Brazil   Americas 1952-01-01   50.917   56602560  2108.944355

In [77]:
# filtro = df.pais == 'Brazil'
df.loc[filtro].sort_values('lifeExp', ascending=False)

       pais continente        ano  lifeExp        pop    pibpercap
386  Brazil   Americas 2007-01-01   72.390  190010647  9065.800825
385  Brazil   Americas 2002-01-01   71.006  179914212  8131.212843
384  Brazil   Americas 1997-01-01   69.388  168546719  7957.980824
383  Brazil   Americas 1992-01-01   67.057  155975974  6950.283021
382  Brazil   Americas 1987-01-01   65.205  142938076  7807.095818
381  Brazil   Americas 1982-01-01   63.336  128962939  7030.835878
380  Brazil   Americas 1977-01-01   61.489  114313951  6660.118654
379  Brazil   Americas 1972-01-01   59.504  100840058  4985.711467
378  Brazil   Americas 1967-01-01   57.632   88049823  3429.864357
377  Brazil   Americas 1962-01-01   55.665   76039390  3336.585802
376  Brazil   Americas 1957-01-01   53.285   65551171  2487.365989
375  Brazil   Americas 1952-01-01   50.917   56602560  2108.944355

In [79]:
filtro = df.ano.dt.year == 2007
df.loc[filtro, ['pais','lifeExp','pop','pibpercap']].sort_values('pop', ascending=False).head(10)

               pais  lifeExp         pop     pibpercap
638           China   72.961  1318683096   4959.114854
1411          India   64.698  1110396331   2452.210407
3216  United States   78.242   301139947  42951.653090
1423      Indonesia   70.650   223547000   3540.651564
386          Brazil   72.390   190010647   9065.800825
2277       Pakistan   65.483   169270617   2605.947580
222      Bangladesh   64.062   150448339   1391.253792
2510         Russia   65.475   142369485  13820.711370
2195        Nigeria   46.859   135031164   2013.977305
1598          Japan   82.603   127467972  31656.068060

In [93]:
filtro1 = df.pibpercap >= 34000
filtro2 = df.ano.dt.year == 2007
# df.loc[filtro, ['pais','lifeExp','pop','pibpercap']].sort_values('pop', ascending=False).head(10)
df.loc[filtro1 & filtro2].sort_values('pibpercap', ascending=False)

                      pais continente  ...        pop    pibpercap
2466                 Qatar       Asia  ...     907229  82010.97804
1828          Macao, China       Asia  ...     456989  54589.82024
2253                Norway     Europe  ...    4627926  49357.19017
394                 Brunei       Asia  ...     386511  48014.58767
1662                Kuwait       Asia  ...    2505559  47306.98978
2601             Singapore       Asia  ...    4553009  47143.17964
3216         United States   Americas  ...  301139947  42951.65309
1460               Ireland     Europe  ...    4109086  40675.99635
1284      Hong Kong, China        NaN  ...    6980412  39724.97867
2943           Switzerland     Europe  ...    7554661  37506.41907
3146  United Arab Emirates       Asia  ...    2642566  36953.68369
2087           Netherlands     Europe  ...   16570613  36797.93332
556                 Canada        NaN  ...   33390141  36319.23501
1399               Iceland     Europe  ...     301931  36180.78919
184                Austria     Europe  ...    8199783  36126.49270
860                Denmark     Europe  ...    5468120  35278.41874
127              Australia        NaN  ...   20434176  34435.36744

[17 rows x 6 columns]